mybatis-plus:
  mapper-locations: classpath*:com/mooc/meetingfilm/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true
#0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mooc_meetingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 111111
    filters: log4j,wall,mergeStat


logging:
  config: classpath:logback.xml
